name: DVTElevator-ci-pipeline (Development)

on:
  push:
    branches:
          - development 
  pull_request:
    branches:
           - main
           - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore NuGet packages
        run: dotnet restore DVTElevator.sln

      - name: Build solution
        run: dotnet build DVTElevator.sln --no-restore --configuration Release

      - name: ✅ Run unit + integration tests with coverage
        run: dotnet test DVTElevator.sln --no-build --configuration Release --collect:"XPlat Code Coverage"

      - name: 📊 Report code coverage summary
        uses: danielpalme/ReportGenerator-GitHub-Action@5
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coverage-report'
          reporttypes: 'MarkdownSummary'
